include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    missing_return: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    use_build_context_synchronously: false
    unnecessary_null_comparison: false
    type_literal_in_constant_pattern: false
