name: termeen
description: termeen app
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 2.15.1
  firebase_auth: 4.9.0
  http: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
